name: CI/CD Pipeline de Entrega Contínua

on:
  push:
    branches: [ "main" ]

jobs:
  build_e_push_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código da aplicação
        uses: actions/checkout@v3

      - name: Debug Docker Username
        run: echo "A pipeline está a tentar usar o utilizador: '${{ secrets.DOCKER_USERNAME }}'"

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/meu-projeto-ci-cd:${{ github.sha }}

      - name: Checkout do repositório de manifestos
        uses: actions/checkout@v3
        with:
          repository: MuriloPetri/meu-projeto-manifests
          token: ${{ secrets.GH_PAT }}
          path: manifests
      
      - name: Atualizar a tag da imagem no deployment.yaml
        run: |
          cd manifests
          sed -i 's|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/meu-projeto-ci-cd:${{ github.sha }}|g' deployment.yaml

      - name: Fazer commit e push da alteração
        run: |
          cd manifests
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          git commit -am "CI: Atualiza a imagem da aplicação para ${{ github.sha }}"
          git push
