# Nome do Workflow
name: CI/CD - Build e Deploy

# Gatilho: Executa sempre que houver um push na branch 'main'
on:
  push:
    branches: [ "main" ]

# Definição dos trabalhos (jobs)
jobs:
  build-and-deploy:
    # O tipo de máquina virtual que o trabalho irá correr
    runs-on: ubuntu-latest

    # Sequência de passos que o trabalho irá executar
    steps:
      # Passo 1: Clona o repositório da aplicação para a máquina virtual
      - name: Checkout do código da aplicação
        uses: actions/checkout@v4

      # Passo 2: Faz o login no Docker Hub com token de acesso (recomendado)
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}  # Troque DOCKER_PASSWORD por DOCKER_TOKEN no GitHub Secrets

      # Passo 3: Constrói a imagem Docker e envia para o Docker Hub
      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/meu-projeto-ci-cd:${{ github.sha }}

      # Passo 4: Clona o repositório de manifestos para uma pasta separada
      - name: Checkout do repositório de manifestos
        uses: actions/checkout@v4
        with:
          repository: MuriloPetri/meu-projeto-manifests
          token: ${{ secrets.GH_PAT }}  # Deve ser um GitHub Token com permissão de escrita no repo de manifestos
          path: manifests

      # Passo 5: Atualiza o ficheiro deployment.yaml com a nova tag da imagem
      - name: Atualizar a tag da imagem no deployment.yaml
        run: |
          cd manifests
          sed -i 's|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/meu-projeto-ci-cd:${{ github.sha }}|g' deployment.yaml

      # Passo 6: Faz o commit e push da alteração para o repositório de manifestos
      - name: Fazer commit e push da alteração no repositório de manifestos
        run: |
          cd manifests
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          git commit -am "CI: Atualiza a imagem da aplicação para o commit ${{ github.sha }}"
          git push
